### ISSUE TITLE
Add more token image sources

### ISSUE THREAD

**Issue by willhennessy** [OffchainLabs/arb-token-lists#3]
Approximately 30 tokens are missing the tokenLogo field, which is a suboptimal user experience. I think we can fix most of them by adding the following two sources to the generator script:

* https://cryptologos.cc/
* https://github.com/coinwink/cryptocurrency-logos

<img width="406" alt="Screen Shot 2021-11-01 at 7 08 53 PM" src="https://user-images.githubusercontent.com/5455577/139753755-ab542fa4-500c-4209-812a-eaa8759c7a20.png">

**Comment by DZGoldman** [comment]
Updated — most have logo sources now
