### ISSUE TITLE
Bridged asset standard

### ISSUE THREAD

**Issue by willhennessy** [OffchainLabs/arb-token-lists#4]
Hi Daniel and team,

Thanks for your feedback on our proposal for standardized token bridging! We're going to proceed with the [proposal](https://github.com/Uniswap/token-lists/issues/51#issuecomment-952268629) and are asking partners across the ecosystem to implement it by December 1 if possible.

Are you up for it?

As a reference example, here is the Optimism team's version: https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/35

Thanks,
Will

**Comment by DZGoldman** [comment]
Sounds good! Will update.

In terms of backwards compatibility with the old/current extension fields (i.e., l1Address is likely the most used), we'll likely just use both the old and the new (originBridgeAddress) one for our current endpoint (https://bridge.arbitrum.io/token-list-42161.json) and only use the new standard for new token list endpoints we create

**Comment by zakaria-ahmed** [comment]
Hi @DZGoldman whats the possibility if a team had a wrong contract address on https://bridge.arbitrum.io/token-list-42161.json to change it ?. 
I believe GMX´s contract there is wrong, the right contract is this one 0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a
so whenever someone attempts to buy on Uniswap currently shows no liquidity

**Comment by DZGoldman** [comment]
(@zakaria-ahmed removed comment as it's not relevant to issue — let's discuss elsewhere, thanks!)
