### ISSUE TITLE
remove "server" subdir and all express dependencies 

### ISSUE THREAD

**Issue by DZGoldman** [OffchainLabs/arb-token-lists#58]

**Comment by ADK0010** [comment]
I would like to work on it.

**Comment by ADK0010** [comment]
Hi  @DZGoldman, I just had a doubt on how to remove the "start_server" from "scripts" section in "package.json" of the issue.
Should I just remove it manually by backspacing it or is their any other specified method to do it.

**Comment by chrstph-dvx** [comment]
Thank you!
