### ISSUE TITLE
switch to github cron task for list gen

### ISSUE THREAD

**Issue by DZGoldman** [OffchainLabs/arb-token-lists#72]
TODOs
- [ ] Run task periodically and generate token lists json artifacts
- [ ] Alert on Slack if task fails
- [ ] Upload the json artifacts to an S3 bucket

Helpful links
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

**Comment by chrstph-dvx** [comment]
Done in https://github.com/OffchainLabs/arb-token-lists/pull/74
