### ISSUE TITLE
allow explicitly provided "prevArbifiedList" and "newArbifiedList" path arguments when arbifying 

### ISSUE THREAD

**Issue by DZGoldman** [OffchainLabs/arb-token-lists#73]
**Currently**:
Arbifying takes only the [L1 list as its input](https://github.com/OffchainLabs/arb-token-lists/blob/0e8c349e962ff712414625230b496daaf5db936f/update_all#L14). From the L1 list's name, it deterministically calculates the arbified lists path (including file name). It uses this path to find a previously-arbified list (to us for versioning) and to write the new list.

This is error prone, since if an L1 list changes its name (as Uniswap has), the location / path of the new arbified list changes as well. It also forces the CL script into using the repo's file structure, which is unnecessary / unideal.

**Fix**
Allow arbification to provide 3 CL arguments:
1. url of external L1 list
2. path to previous arbified list (optional / if it exists)
3. path to new arbified list (i.e., where to write it)

(Note that to retain current behavior, arguments to  2 and 3 would simply be the same path)

**Comment by Jason-Wanxt** [comment]
How about we also make `update` as this:
If `pathOrUrl` is `path`, write the updated list to this path, 
If `pathOrUrl` is `url`, retain current behavior.

**Comment by Jason-Wanxt** [comment]
Thought we might add this functionality to `update` rather than `arbify`?

**Comment by DZGoldman** [comment]
We can / should add this functionality to both update and arbify; adding it to arbify is more pressing (just b/c we use it more). The idea is arbify would still work exactly as it does now (input an L1 list and generate a new L2 list), the only difference is, instead of automatically calculating the new filename/path for the new list, it uses whatever filename/path that the caller provide. So in the new version, filename/path is completely decoupled from the list "name" (i.e., thing that appears in the name field).

`preserveListName` has to do with the "name" (thing in the "name" field), not the filename/path, so is unrelated to this issue.

**Comment by Jason-Wanxt** [comment]
Make sense!
