### ISSUE TITLE
Backwards compatibility broken in https://bridge.arbitrum.io/token-list-42161.json

### ISSUE THREAD

**Issue by welps** [OffchainLabs/arb-token-lists#8]
Hello, in https://github.com/OffchainLabs/arb-token-lists/issues/4#issuecomment-966599906 it's stated that the current endpoint would remain backwards compatible while supporting the new standard

> In terms of backwards compatibility with the old/current extension fields (i.e., l1Address is likely the most used), we'll likely just use both the old and the new (originBridgeAddress) one for our current endpoint (https://bridge.arbitrum.io/token-list-42161.json) and only use the new standard for new token list endpoints we create

But this no longer seems to be the case after the release of #5 as it broke one of my integrations. Is this intentional? An example from https://bridge.arbitrum.io/token-list-42161.json

```
    {
      "chainId": 42161,
      "address": "0x03b95f1C84Af0607afd5dD87ca1FDE7572aa827F",
      "name": "Agave",
      "symbol": "AGVE",
      "decimals": 18,
      "extensions": {
        "bridgeInfo": {
          "1": {
            "tokenAddress": "0x0b006e475620af076915257c6a9e40635abdbbad",
            "originBridgeAddress": "0x09e9222e96e7b4ae2a407b98d48e330053351eee",
            "destBridgeAddress": "0xa3A7B6F88361F48403514059F1F16C8E78d60EeC"
          }
        }
      }
    }
```

**Comment by DZGoldman** [comment]
woops, you're right, this was an oversight, will update asap!

**Comment by welps** [comment]
Thanks for the quick fix!
