### ISSUE TITLE
Add $REUNI to the token lists

### ISSUE THREAD

**Issue by GoldenNaim** [OffchainLabs/arb-token-lists#92]
GM !
I don't know the process to add $REUNI to your token lists " arbed_arb_whitelist_era.json ".

So here is the specifications :

Token Address: [0x9ed7E4B1BFF939ad473dA5E7a218C771D1569456](https://arbiscan.io/token/0x9ed7E4B1BFF939ad473dA5E7a218C771D1569456)
Token Name (from contract): Reunit token
Token Decimals (from contract): 6
Token Symbol (from contract): Reuni
Uniswap V3 Pair Address of Token: 0xc09254d1be9c3b7335021873546ba480383981d9

Link to the official homepage of token: https://everywhere.finance/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/reunit-wallet

**Comment by TucksonDev** [comment]
Hello!
We currently don't support adding new tokens to that list. 
In any case, I see that your token is already in the CMC list, so whevener someone searches by the token name or address, it appears as an option to import it.
